name: Continuous Integration

on:
    pull_request:
        branches: [ master ]


jobs:
    test_pull_request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Dependencies
              run: npm install
            - name: Test Project
              run: npm run check-lint
            - name: Build Project
              run: npm build